### PR TITLE
[Fix #278] find-symbol memory leak fix

### LINKED ISSUE #278: find-symbol leads to OutOfMemoryError
##  Expected behavior
`find-symbol` should return list of symbol occurences

## Actual behavior
In some cases `find-symbol` ends up enormous memory consumption resulting in OutOfMemoryError. Partial results are returned.

This issue may be a duplicate of https://github.com/clojure-emacs/refactor-nrepl/issues/245

Following is the stack trace:

```clojure
#error {
 :cause Java heap space
 :via
 [{:type java.lang.OutOfMemoryError
   :message Java heap space
   :at [java.util.Arrays copyOf Arrays.java 3746]}]
 :trace
 [[java.util.Arrays copyOf Arrays.java 3746]
  [java.lang.AbstractStringBuilder ensureCapacityInternal AbstractStringBuilder.java 227]
  [java.lang.AbstractStringBuilder append AbstractStringBuilder.java 593]
  [java.lang.StringBuffer append StringBuffer.java 306]
  [java.io.StringWriter write StringWriter.java 106]
  [clojure.core$fn__7280 invokeStatic core_print.clj 124]
  [clojure.core$fn__7280 invoke core_print.clj 123]
  [clojure.lang.MultiFn invoke MultiFn.java 234]
  [clojure.core$pr_on invokeStatic core.clj 3674]
  [clojure.core$pr_on invoke core.clj 3668]
  [clojure.core$print_prefix_map$fn__7332 invoke core_print.clj 233]
  [clojure.core$print_sequential invokeStatic core_print.clj 66]
  [clojure.core$print_prefix_map invokeStatic core_print.clj 229]
  [clojure.core$print_map invokeStatic core_print.clj 238]
  [clojure.core$fn__7359 invokeStatic core_print.clj 266]
  [clojure.core$fn__7359 invoke core_print.clj 263]
  [clojure.lang.MultiFn invoke MultiFn.java 234]
  [clojure.core$pr_on invokeStatic core.clj 3674]
  [clojure.core$pr_on invoke core.clj 3668]
  [clojure.core$print_prefix_map$fn__7332 invoke core_print.clj 233]
  [clojure.core$print_sequential invokeStatic core_print.clj 66]
  [clojure.core$print_prefix_map invokeStatic core_print.clj 229]
  [clojure.core$print_map invokeStatic core_print.clj 238]
  [clojure.core$fn__7359 invokeStatic core_print.clj 266]
  [clojure.core$fn__7359 invoke core_print.clj 263]
  [clojure.lang.MultiFn invoke MultiFn.java 234]
  [clojure.core$pr_on invokeStatic core.clj 3674]
  [clojure.core$pr_on invoke core.clj 3668]
  [clojure.core$print_prefix_map$fn__7332 invoke core_print.clj 233]
  [clojure.core$print_sequential invokeStatic core_print.clj 66]
  [clojure.core$print_prefix_map invokeStatic core_print.clj 229]
  [clojure.core$print_map invokeStatic core_print.clj 238]]}
```

This is memory usage right before calling a `find-symbol`:

main_-_YourKit_Java_Profiler_2018_04-b88_-_64-bit

and here is how memory consumption looks like during- and after `find-symbol`:

main_-_YourKit_Java_Profiler_2018_04-b88_-_64-bit

### PR DESCRIPTION
**Pull request by mbuczko**
Before I found a real cause of memory leak I tried to analyze and optimize all the functions that are called within `find-symbol` hoping that one of them was the culprit. Eventually I found this line: `(str/join "/" (remove nil? [full-class (:field node)]))))` which was the direct problem.

Looks like `full-class` may become a really huge map in some cases, huge (or complicated) enough that it cannot be stringified correctly by `str/join` which immediately leads to a memory leak.

Having found the real cause, I didn't rollback all the optimization I did before. Hopefully you will find them useful. If not, I'm happy to roll them back.

### CODE REVIEW

File: src/refactor_nrepl/analyzer.clj [hunk 1]
```diff
@@ -28,16 +28,17 @@
...
-        aliases (->> ns-decl
-                     (filter list?)
-                     (some #(when (#{:require} (first %)) %))
-                     rest
-                     (remove symbol?)
-                     (filter #(contains? (set %) :as))
-                     (#(zipmap (map (partial get-alias nil) %)
-                               (map first %))))]
-    [(second ns-decl) aliases]))
+  (with-open [string-reader (java.io.StringReader. body)]
```
Comment (mbuczko) [inline src/refactor_nrepl/analyzer.clj]: wrapped with `with-open` to be sure nothing leaks from non-closed reader.

File: src/refactor_nrepl/find/find_symbol.clj [hunk 2]
```diff
@@ -24,12 +24,12 @@
...
         full-class (get alias-info class class)]
-    (str/join "/" (remove nil? [full-class (:field node)]))))
+    (str/join "/" (remove nil? [(if (map? full-class) "" full-class) (:field node)]))))
 
 (defn- contains-var?
   "Checks if the var of `node` is present in the `var-set`."
-  [vars-set alias-info node]
-  (vars-set (node->var alias-info node)))
+  [var-name alias-info node]
+  (= var-name (node->var alias-info node)))
```
Comment (mbuczko) [inline src/refactor_nrepl/find/find_symbol.clj]: looks like `node->var` returns a single string and the `var-set` iself is a one-element set created in `contains-var-or-const?` as `#{var-name}`. single comparison should be enough here, I guess?

File: src/refactor_nrepl/find/find_symbol.clj [hunk 3]
```diff
@@ -103,41 +102,42 @@
          (str/join "\n")
          str/trim)))
 
-(defn- find-symbol-in-file [fully-qualified-name ignore-errors ^File file]
+(defn- find-symbol-in-file [fully-qualified-name ignore-errors referred-syms ^File file]
```
Comment (mbuczko) [inline src/refactor_nrepl/find/find_symbol.clj]: as I understand, `referred-syms` doesn't have to be called each time. it can be calculated once in `find-global-symbol` and passed here. otherwise it's being unnecessarily called each time for each .clj file.

File: src/refactor_nrepl/find/find_symbol.clj [hunk 4]
```diff
@@ -103,41 +102,42 @@
...
+                                       (:line-end  info))}))]
     (map gather locs)))
 
 (defn- find-global-symbol [file ns var-name ignore-errors]
   (let [namespace (or ns (core/ns-from-string (slurp file)))
         fully-qualified-name (if (= namespace "clojure.core")
                                var-name
-                               (str/join "/" [namespace var-name]))]
+                               (str/join "/" [namespace var-name]))
+        referred-syms (libspecs/referred-syms-by-file&fullname)]
```
Comment (mbuczko) [inline src/refactor_nrepl/find/find_symbol.clj]: calculating `referred-syms` once and passing result to each call of `find-symbol-in-file fully-qualified-name`

File: src/refactor_nrepl/find/find_symbol.clj [hunk 5]
```diff
@@ -228,20 +228,22 @@
                  (map (partial occurrence-for-optmap-default var-name)))]
         (sort-by :line-beg (concat local-occurrences optmap-def-occurrences))))))
 
-(defn- to-find-symbol-result
```
Comment (mbuczko) [inline src/refactor_nrepl/find/find_symbol.clj]: seems like it's not being used anywhere else in a code

File: src/refactor_nrepl/find/find_symbol.clj [hunk 6]
```diff
@@ -228,20 +228,22 @@
...
                      (remove find-util/spurious?)
                      future)]
+
     (or
      ;; find-local-symbol is the fastest of the three
-     (not-empty (remove find-util/spurious? (distinct (find-local-symbol file name line column))))
+     ;; if result is not empty, there is no point in keeping `find-macro` and `find-global-symbol` futures still active
+     (when-let [result (not-empty (remove find-util/spurious? (distinct (find-local-symbol file name line column))))]
+       (future-cancel macros)
+       (future-cancel globals)
```
Comment (mbuczko) [inline src/refactor_nrepl/find/find_symbol.clj]: having found local-symbol we may cancel previously run (and potentially CPU intensive) futures looking for macros and global symbols?

File: src/refactor_nrepl/find/find_symbol.clj [hunk 7]
```diff
@@ -58,8 +58,7 @@
         (map (juxt (comp :line :env)
                    (comp :end-line :env)
                    (comp :column :env)
-                   (comp :end-column :env)
-                   pred))
```
Comment (mbuczko) [inline src/refactor_nrepl/find/find_symbol.clj]: having a `pred` here instructs `juxt` to call 5 functions on a mapped values (producing 5 results), however `zipmap` below goes with 4 elements: `:line-beg :line-end :col-beg :col-end` which, as I understand, ignores last "juxted" value produced by `pred`?

File: src/refactor_nrepl/middleware.clj [hunk 8]
```diff
@@ -54,7 +54,7 @@
   `(with-errors-being-passed-on ~transport ~msg
      (config/with-config ~msg
        (transport/send ~transport
-                       (response-for ~msg ~(apply hash-map :status :done kvs))))))
```
Comment (mbuczko) [inline src/refactor_nrepl/middleware.clj]: looks like all reply-functions below call this macro with `:status :done` (all except `find-used-locals-reply`). if so, maybe it would be better to get rid of status from here and use `reply` in `find-symbol-reply` which would simplify the code and make it more DRY-ish?

File: src/refactor_nrepl/middleware.clj [hunk 9]
```diff
@@ -138,7 +133,7 @@
    (require-and-resolve 'refactor-nrepl.find.find-locals/find-used-locals)))
 
 (defn- find-used-locals-reply [{:keys [transport] :as msg}]
-  (reply transport msg :used-locals (@find-used-locals msg)))
+  (reply transport msg :used-locals (@find-used-locals msg) :status :done))
```
Comment (mbuczko) [inline src/refactor_nrepl/middleware.clj]: this is was the only place relying on `:status :done` in `reply` macro.

**Comment by expez** [comment]
Would you mind updating the commit message so it matches the rest of the commits in the git log?
What's in the header of this PR is basically that: `[Fix #278] Memory leak in find-symbol`

**Comment by mbuczko** [comment]
> Would you mind updating the commit message so it matches the rest of the commits in the git log?
> What's in the header of this PR is basically that: `[Fix #278] Memory leak in find-symbol`

done. thanks for review!
